project:
  type: book

book:
  title: "TailWinds Guide"
  author: "Mike O'Brien, with others in the future"
  date: last-modified
  chapters:
    - index.qmd
    - part: website/index.qmd
      chapters:
        - website/01_downloading.qmd
        - website/02_git.qmd
        - website/03_clone.qmd
        - website/04_branch.qmd
        - website/05_write.qmd
        - website/06_commit.qmd
        - website/07_pull.qmd
        - website/08_push.qmd
        - website/09_pull_request.qmd
    - part: guide/index.qmd
      chapters: 
        - guide/01_editing.qmd
    - part: frm/index.qmd
      chapters:
        - frm/01_pot.qmd
        - frm/02_knots.qmd
        - frm/03_rec.qmd
        - frm/04_dissection.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



