project:
  type: book

book:
  title: "TailWinds Guide"
  author: "Mike O'Brien, with others in the future"
  date: last-modified
  chapters:
    - index.qmd
    - part: website/website_intro.qmd
      chapters:
        - website/01_downloading.qmd
        - website/02_git.qmd
        - website/03_clone.qmd
        - website/04_branch.qmd
        - website/05_write.qmd
        - website/06_commit.qmd
        - website/07_pull.qmd
        - website/08_push.qmd
        - website/09_pull_request.qmd
    - 02_guide.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



