# Preface and Definitions {.unnumbered}

This guide is intended to be a place to host our accumulated institutional knowledge and standard operating procedures regarding the TailWinds project. We've already had mild amounts of staff turnover, so the hope is that this will alleviate some of the pain associated with onboarding -- or "re-onboarding" our current members after periods away from the project.

Inspired by [Gavin Fay's Lab Manual](https://thefaylab.github.io/lab-manual/), this is a living document which everyone should be able to edit.

## Acronyms

-   EFP: Exempted Fishing Permit
-   IACUC: Institutional Animal Care and Use Committee
-   LOA: Letter of Authorization
-   MMM: Marine Mammal Monitoring. One of the three core TailWinds projects. Include FRS #?
-   FRM: Fishery Resource Monitoring. One of the three core TailWinds projects. Include FRS #?
-   RTWB: (Near) Real-Time Whale Buoy. One of the three core TailWinds projects. FRS #?

## Definitions

-   Console: Where you type commands into R.
-   Terminal: Command-line interface to the computer. Access in RStudio via Tools \> Terminal \> New Terminal
