# TailWinds Guide

A guide for the *guide*. Heaven help us.

This guide and the TailWinds website were built using [Quarto](https://quarto.org/) and the tools provided in [RStudio](https://posit.co/downloads/). You can use other tools, it's just what we're most familiar with, so that's what we'll use to walk through the larger concepts. The next sections give a general view of Quarto, Git, and YAML; these were developed by trial-and-error and a lot of failing. Hopefully we can use this as reference.

## Source vs Visual editor

Pretty much everything you write for the Guide (and the website) will use Markdown. Some basics are outlined on the [Quarto website](https://quarto.org/docs/authoring/markdown-basics.html). Note that if you're Googling for something related to Markdown formatting, anything sold as "RMarkdown" will also work.

All of the different options can be confusing and create a barrier to entry. Enter: the RStudio Visual Markdown editor.

RStudio has a visual editor for markdown documents (also called a "what-you-see-is-what-you-get" editor, or WYSIWYG, or "wizzy-wig", how fun!). You can activate this by clicking "Visual" in the top left of your code editing pane. Now, R will act as if it were MS Word, allowing you to skip the code and add things with a few clicks. If you're curious as to what the markdown code looks like, click "Source" and it will switch to editing as if you were a coding expert.
