# Pull

No, we're not shooting skeet.

There will probably come a time when someone has made changes to the website between the time that you last downloaded things from GitHub and now. If you try to send your changes (commits) back up to GitHub, it will stop and let you know that things have changed.

In order to get ahead of this, click the "Pull" button. This will ***pull*** the changes from GitHub onto your computer. Hopefully, it'll go ahead and merge everything together for you. If it can't -- usually when you have edited the same lines that someone else has -- it will combine the two versions of the files and ask you to sort it out. This usually means opening the files and making an executive decision about what text/code you wish to keep.

## `git merge`

If you're working on a development branch (something that isn't `main`), you'll often find that `main` will sometimes get ahead of you. Maybe there's been a quick add directly to `main`, or some other development branch has been merged in.

To bring your development branch up to date with these changes, switch to the development branch (either through the drop-down button on the right hand side of RStudio's git pane or via `git branch YOUR-DEV-BRANCH`) and run the following in your terminal:

```
git merge main
```

This will bring all of the changes that have been made to main that your current branch does not have. Then, `git push` these back to GitHub to tidy everything up.
