# Push

Take a deep breath, like Lamaze for your code.

Now that everything is in line, compile the website one more time via **Build \> Render**, commit changes, and click the "Push" button. This pushes all of the changes you've logged on your computer (via commits) to GitHub. If you've been editing the master branch, this will automatically change the website.

If you've been editing in your own branch, things are less stressful. A new branch is your own little sandbox -- nothing will get added to the website before it's approved by Mike. To get that done, you need to open a pull request (next section).

If you get an error that looks like this...

    remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
    remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
    fatal: Authentication failed for 'https://github.com/OWNER/REPO.git/'

...you need to let GitHub know that you're allowed to make changes to your account. Refer back to the section on [installing Git](02_git.html#connecting-your-computer-to-github).
